{
    'name': 'Announcement Disable',
    'version': '0.1',
    'category': 'Extra Tools',
    'summary': 'Disables the announcement bar',
    'description': """Disables the announcement bar""",
    'images': [],
    'author': 'Bubbles-IT',
    'maintainer': 'Bubbles-IT',
    'website': 'http://www.bubbles-it.be',
    'depends': ['mail'],
    'data': ['announcement_view.xml'],
    'demo': [],
    'css': [],
    'js': [],
    'qweb': [],
    'test': [],
    'installable': True,
    'application': False,
    'auto_install': False,
}
