-
  Create some tags
-
  !record {model: xx.product.supplierinfo.tags, id: tag_id_1000}:
    name: 1000
    res_model: 'product.supplierinfo'
    res_id: !eval ref("product.product_supplierinfo_1")
-
  !record {model: xx.product.supplierinfo.tags, id: tag_id_1001}:
    name: 1001
    res_model: 'product.supplierinfo'
    res_id: !eval ref("product.product_supplierinfo_1")
-
  !record {model: xx.product.supplierinfo.tags, id: tag_id_1003}:
    name: 1003
    res_model: 'product.supplierinfo'
    res_id: !eval ref("product.product_supplierinfo_1")
-
  !python {model: product.supplierinfo}: |
    id = ref("product.product_supplierinfo_1")
    vals = {'product_name':'test', 'xx_tag_ids': [(6,0,[ref('tag_id_1000'),ref('tag_id_1001'),ref('tag_id_1003')])]}
    self.write(cr, uid, id, vals)